import { getDb, insertHsn, insertPincode } from '../db.js';

const HSN_CODES = [
  // Chapter 1-5: Animal products
  { code: '0101', description: 'Live horses, asses, mules and hinnies', gst_rate: 0, category: 'Live Animals' },
  { code: '0102', description: 'Live bovine animals', gst_rate: 0, category: 'Live Animals' },
  { code: '0201', description: 'Meat of bovine animals, fresh or chilled', gst_rate: 0, category: 'Meat' },
  { code: '0301', description: 'Live fish', gst_rate: 0, category: 'Fish' },
  { code: '0401', description: 'Milk and cream, not concentrated', gst_rate: 0, category: 'Dairy' },
  { code: '0402', description: 'Milk and cream, concentrated or with sugar', gst_rate: 12, category: 'Dairy' },
  { code: '0406', description: 'Cheese and curd', gst_rate: 12, category: 'Dairy' },
  { code: '0407', description: 'Birds eggs, in shell, fresh', gst_rate: 0, category: 'Eggs' },
  // Chapter 6-14: Vegetable products
  { code: '0601', description: 'Bulbs, tubers, plants for planting', gst_rate: 0, category: 'Plants' },
  { code: '0701', description: 'Potatoes, fresh or chilled', gst_rate: 0, category: 'Vegetables' },
  { code: '0702', description: 'Tomatoes, fresh or chilled', gst_rate: 0, category: 'Vegetables' },
  { code: '0703', description: 'Onions, shallots, garlic, leeks', gst_rate: 0, category: 'Vegetables' },
  { code: '0801', description: 'Coconuts, Brazil nuts and cashew nuts, fresh', gst_rate: 0, category: 'Nuts' },
  { code: '0901', description: 'Coffee, whether or not roasted', gst_rate: 5, category: 'Beverages' },
  { code: '0902', description: 'Tea, whether or not flavoured', gst_rate: 5, category: 'Beverages' },
  // Chapter 10: Cereals
  { code: '1001', description: 'Wheat and meslin', gst_rate: 0, category: 'Cereals' },
  { code: '1002', description: 'Rye', gst_rate: 0, category: 'Cereals' },
  { code: '1003', description: 'Barley', gst_rate: 0, category: 'Cereals' },
  { code: '1004', description: 'Oats', gst_rate: 0, category: 'Cereals' },
  { code: '1005', description: 'Maize (corn)', gst_rate: 0, category: 'Cereals' },
  { code: '1006', description: 'Rice', gst_rate: 0, category: 'Cereals' },
  { code: '1007', description: 'Grain sorghum', gst_rate: 0, category: 'Cereals' },
  // Chapter 15: Animal/vegetable fats
  { code: '1501', description: 'Pig fat; poultry fat', gst_rate: 12, category: 'Fats and Oils' },
  { code: '1507', description: 'Soya-bean oil and its fractions', gst_rate: 5, category: 'Fats and Oils' },
  { code: '1511', description: 'Palm oil and its fractions', gst_rate: 5, category: 'Fats and Oils' },
  { code: '1514', description: 'Rapeseed or mustard oil', gst_rate: 5, category: 'Fats and Oils' },
  // Chapter 17: Sugar
  { code: '1701', description: 'Cane or beet sugar and chemically pure sucrose', gst_rate: 5, category: 'Sugar' },
  { code: '1704', description: 'Sugar confectionery not containing cocoa', gst_rate: 18, category: 'Confectionery' },
  // Chapter 18: Cocoa
  { code: '1801', description: 'Cocoa beans, whole or broken, raw or roasted', gst_rate: 5, category: 'Cocoa' },
  { code: '1806', description: 'Chocolate and other food preparations containing cocoa', gst_rate: 18, category: 'Chocolate' },
  // Chapter 19: Preparations of cereals
  { code: '1901', description: 'Malt extract; food preparations of flour, groats', gst_rate: 18, category: 'Food Prep' },
  { code: '1902', description: 'Pasta, whether or not cooked', gst_rate: 12, category: 'Food Prep' },
  { code: '1905', description: 'Bread, pastry, cakes, biscuits and other bakers wares', gst_rate: 18, category: 'Baked Goods' },
  // Chapter 21: Miscellaneous edible preparations
  { code: '2101', description: 'Extracts, essences and concentrates of coffee, tea or mate', gst_rate: 12, category: 'Beverages' },
  { code: '2106', description: 'Food preparations not elsewhere specified', gst_rate: 18, category: 'Food Prep' },
  // Chapter 22: Beverages
  { code: '2201', description: 'Waters, including natural or artificial mineral waters', gst_rate: 12, category: 'Beverages' },
  { code: '2202', description: 'Waters with added sugar, flavouring or other substances', gst_rate: 18, category: 'Beverages' },
  { code: '2203', description: 'Beer made from malt', gst_rate: 28, category: 'Beverages' },
  { code: '2204', description: 'Wine of fresh grapes', gst_rate: 28, category: 'Beverages' },
  { code: '2207', description: 'Ethyl alcohol, undenatured of alcoholic strength >= 80%', gst_rate: 18, category: 'Spirits' },
  // Chapter 24: Tobacco
  { code: '2401', description: 'Unmanufactured tobacco; tobacco refuse', gst_rate: 5, category: 'Tobacco' },
  { code: '2402', description: 'Cigars, cheroots, cigarillos and cigarettes', gst_rate: 28, category: 'Tobacco' },
  // Chapter 25: Mineral products
  { code: '2501', description: 'Salt; pure sodium chloride', gst_rate: 0, category: 'Minerals' },
  { code: '2523', description: 'Portland cement, aluminous cement, slag cement', gst_rate: 28, category: 'Construction' },
  // Chapter 27: Mineral fuels
  { code: '2701', description: 'Coal; briquettes, ovoids and similar solid fuels', gst_rate: 5, category: 'Fuels' },
  { code: '2710', description: 'Petroleum oils and oils from bituminous minerals', gst_rate: 18, category: 'Fuels' },
  // Chapter 28-29: Chemicals
  { code: '2804', description: 'Hydrogen, rare gases and other non-metals', gst_rate: 18, category: 'Chemicals' },
  { code: '2901', description: 'Acyclic hydrocarbons', gst_rate: 18, category: 'Chemicals' },
  // Chapter 30: Pharmaceutical products
  { code: '3001', description: 'Glands and other organs for organo-therapeutic uses', gst_rate: 12, category: 'Pharma' },
  { code: '3004', description: 'Medicaments, for retail sale', gst_rate: 12, category: 'Pharma' },
  { code: '3005', description: 'Wadding, gauze, bandages and similar articles', gst_rate: 12, category: 'Medical' },
  // Chapter 33: Cosmetics
  { code: '3301', description: 'Essential oils, whether or not terpeneless', gst_rate: 18, category: 'Cosmetics' },
  { code: '3304', description: 'Beauty or make-up preparations and skin care preparations', gst_rate: 18, category: 'Cosmetics' },
  { code: '3305', description: 'Preparations for use on hair', gst_rate: 18, category: 'Cosmetics' },
  { code: '3307', description: 'Pre-shave, shaving or after-shave preparations', gst_rate: 18, category: 'Cosmetics' },
  // Chapter 34: Soap
  { code: '3401', description: 'Soap; organic surface-active products for use as soap', gst_rate: 18, category: 'Soap' },
  { code: '3402', description: 'Organic surface-active agents; washing preparations', gst_rate: 18, category: 'Cleaning' },
  // Chapter 39: Plastics
  { code: '3901', description: 'Polymers of ethylene, in primary forms', gst_rate: 18, category: 'Plastics' },
  { code: '3923', description: 'Articles for conveyance or packing of goods, of plastics', gst_rate: 18, category: 'Plastics' },
  // Chapter 40: Rubber
  { code: '4011', description: 'New pneumatic tyres, of rubber', gst_rate: 28, category: 'Rubber' },
  // Chapter 44: Wood
  { code: '4401', description: 'Fuel wood, in logs, in billets, in twigs, in faggots', gst_rate: 0, category: 'Wood' },
  { code: '4412', description: 'Plywood, veneered panels and similar laminated wood', gst_rate: 12, category: 'Wood' },
  // Chapter 48: Paper
  { code: '4801', description: 'Newsprint, in rolls or sheets', gst_rate: 5, category: 'Paper' },
  { code: '4802', description: 'Uncoated paper and paperboard, for writing/printing', gst_rate: 12, category: 'Paper' },
  // Chapter 49: Books
  { code: '4901', description: 'Printed books, brochures, leaflets and similar printed matter', gst_rate: 0, category: 'Books' },
  { code: '4902', description: 'Newspapers, journals and periodicals', gst_rate: 0, category: 'Books' },
  // Chapter 50-63: Textiles
  { code: '5001', description: 'Silk-worm cocoons suitable for reeling', gst_rate: 0, category: 'Textiles' },
  { code: '5101', description: 'Wool, not carded or combed', gst_rate: 0, category: 'Textiles' },
  { code: '5201', description: 'Cotton, not carded or combed', gst_rate: 0, category: 'Textiles' },
  { code: '5208', description: 'Woven fabrics of cotton, >= 85% cotton, <= 200g/m2', gst_rate: 5, category: 'Textiles' },
  { code: '6101', description: 'Mens or boys overcoats, car-coats, cloaks', gst_rate: 5, category: 'Clothing' },
  { code: '6201', description: 'Mens or boys overcoats, car-coats, capes', gst_rate: 12, category: 'Clothing' },
  // Chapter 61-62: Apparel
  { code: '6101', description: 'Mens overcoats, knitted or crocheted', gst_rate: 5, category: 'Apparel' },
  { code: '6109', description: 'T-shirts, singlets and other vests, knitted or crocheted', gst_rate: 12, category: 'Apparel' },
  // Chapter 64: Footwear
  { code: '6401', description: 'Waterproof footwear with outer soles and uppers of rubber', gst_rate: 18, category: 'Footwear' },
  { code: '6403', description: 'Footwear with outer soles of rubber and uppers of leather', gst_rate: 18, category: 'Footwear' },
  // Chapter 72-73: Iron and steel
  { code: '7201', description: 'Pig iron and spiegeleisen in pigs, blocks or other primary forms', gst_rate: 18, category: 'Steel' },
  { code: '7208', description: 'Flat-rolled products of iron, hot-rolled', gst_rate: 18, category: 'Steel' },
  // Chapter 84: Machinery
  { code: '8401', description: 'Nuclear reactors; fuel elements for nuclear reactors', gst_rate: 18, category: 'Machinery' },
  { code: '8415', description: 'Air conditioning machines', gst_rate: 28, category: 'Appliances' },
  { code: '8418', description: 'Refrigerators, freezers and other refrigerating equipment', gst_rate: 18, category: 'Appliances' },
  { code: '8419', description: 'Machinery for treating materials by temperature change', gst_rate: 18, category: 'Machinery' },
  { code: '8421', description: 'Centrifuges; filtering or purifying machinery', gst_rate: 18, category: 'Machinery' },
  { code: '8443', description: 'Printing machinery; machines for reading barcode', gst_rate: 18, category: 'Machinery' },
  { code: '8450', description: 'Household or laundry-type washing machines', gst_rate: 28, category: 'Appliances' },
  { code: '8471', description: 'Automatic data processing machines; computers', gst_rate: 18, category: 'IT Equipment' },
  { code: '8472', description: 'Other office machines (duplicating machines, etc.)', gst_rate: 18, category: 'IT Equipment' },
  { code: '8473', description: 'Parts and accessories for computers and office machines', gst_rate: 18, category: 'IT Equipment' },
  // Chapter 85: Electrical equipment
  { code: '8501', description: 'Electric motors and generators', gst_rate: 18, category: 'Electrical' },
  { code: '8504', description: 'Electrical transformers, static converters and inductors', gst_rate: 18, category: 'Electrical' },
  { code: '8517', description: 'Telephone sets; smartphones and other phones', gst_rate: 18, category: 'Electronics' },
  { code: '8518', description: 'Microphones and stands; loudspeakers; headphones', gst_rate: 18, category: 'Electronics' },
  { code: '8521', description: 'Video recording or reproducing apparatus', gst_rate: 18, category: 'Electronics' },
  { code: '8525', description: 'Transmission apparatus for radio-broadcasting, television', gst_rate: 18, category: 'Electronics' },
  { code: '8528', description: 'Monitors and projectors; reception apparatus for television', gst_rate: 28, category: 'Electronics' },
  { code: '8536', description: 'Electrical apparatus for switching or protecting electrical circuits', gst_rate: 18, category: 'Electrical' },
  { code: '8540', description: 'Thermionic, cold cathode or photo-cathode valves and tubes', gst_rate: 18, category: 'Electronics' },
  { code: '8541', description: 'Semiconductor devices; light-emitting diodes (LEDs)', gst_rate: 18, category: 'Electronics' },
  { code: '8542', description: 'Electronic integrated circuits', gst_rate: 18, category: 'Electronics' },
  // Chapter 87: Vehicles
  { code: '8701', description: 'Tractors (other than tractors of heading 8709)', gst_rate: 12, category: 'Vehicles' },
  { code: '8702', description: 'Motor vehicles for transport of >= 10 persons', gst_rate: 28, category: 'Vehicles' },
  { code: '8703', description: 'Motor cars and other motor vehicles for transport of persons', gst_rate: 28, category: 'Vehicles' },
  { code: '8711', description: 'Motorcycles (including mopeds) and cycles with auxiliary motor', gst_rate: 28, category: 'Vehicles' },
  { code: '8714', description: 'Parts and accessories for vehicles of headings 8711 to 8713', gst_rate: 28, category: 'Vehicles' },
  // Chapter 90: Optical instruments
  { code: '9001', description: 'Optical fibres and optical fibre bundles', gst_rate: 12, category: 'Optics' },
  { code: '9006', description: 'Photographic cameras; flash apparatus', gst_rate: 18, category: 'Cameras' },
  { code: '9018', description: 'Instruments and appliances for medical, surgical use', gst_rate: 12, category: 'Medical' },
  // Chapter 94: Furniture
  { code: '9401', description: 'Seats (other than those of heading 9402)', gst_rate: 18, category: 'Furniture' },
  { code: '9403', description: 'Other furniture and parts thereof', gst_rate: 18, category: 'Furniture' },
  { code: '9404', description: 'Mattress supports; mattresses, quilts, pillows', gst_rate: 18, category: 'Furniture' },
  // Chapter 95: Toys
  { code: '9501', description: 'Wheeled toys designed to be ridden; dolls carriages', gst_rate: 12, category: 'Toys' },
  { code: '9503', description: 'Toys and models, with or without motor', gst_rate: 12, category: 'Toys' },
  // Chapter 96: Miscellaneous
  { code: '9601', description: 'Worked ivory, bone, tortoise-shell, horn, coral, etc.', gst_rate: 28, category: 'Misc' },
  { code: '9619', description: 'Sanitary towels, tampons, napkins and similar articles', gst_rate: 12, category: 'Hygiene' },
  // SAC Codes (Services)
  { code: '9954', description: 'Construction services of buildings', gst_rate: 18, category: 'Services - Construction' },
  { code: '9961', description: 'Services in wholesale trade', gst_rate: 18, category: 'Services - Trade' },
  { code: '9962', description: 'Services in retail trade', gst_rate: 18, category: 'Services - Trade' },
  { code: '9963', description: 'Accommodation, food and beverage services', gst_rate: 18, category: 'Services - Hospitality' },
  { code: '9964', description: 'Passenger transport services', gst_rate: 5, category: 'Services - Transport' },
  { code: '9965', description: 'Goods transport services', gst_rate: 5, category: 'Services - Transport' },
  { code: '9966', description: 'Rental services of transport vehicles', gst_rate: 18, category: 'Services - Rental' },
  { code: '9967', description: 'Supporting services in transport', gst_rate: 18, category: 'Services - Transport' },
  { code: '9968', description: 'Postal and courier services', gst_rate: 18, category: 'Services - Communication' },
  { code: '9969', description: 'Electricity, gas, water and other distribution services', gst_rate: 18, category: 'Services - Utilities' },
  { code: '9971', description: 'Financial and related services', gst_rate: 18, category: 'Services - Financial' },
  { code: '9972', description: 'Real estate services', gst_rate: 18, category: 'Services - Real Estate' },
  { code: '9973', description: 'Leasing or rental services without operator', gst_rate: 18, category: 'Services - Leasing' },
  { code: '9981', description: 'Research and development services', gst_rate: 18, category: 'Services - R&D' },
  { code: '9982', description: 'Legal and accounting services', gst_rate: 18, category: 'Services - Professional' },
  { code: '9983', description: 'Other professional, technical and business services including IT', gst_rate: 18, category: 'Services - IT' },
  { code: '9984', description: 'Telecommunications, broadcasting and information supply services', gst_rate: 18, category: 'Services - Telecom' },
  { code: '9985', description: 'Support services', gst_rate: 18, category: 'Services - Support' },
  { code: '9986', description: 'Agriculture, forestry, fishing, mining support services', gst_rate: 0, category: 'Services - Agriculture' },
  { code: '9987', description: 'Maintenance, repair and installation (except construction)', gst_rate: 18, category: 'Services - Repair' },
  { code: '9988', description: 'Manufacturing services on physical inputs owned by others', gst_rate: 18, category: 'Services - Manufacturing' },
  { code: '9989', description: 'Other manufacturing services', gst_rate: 18, category: 'Services - Manufacturing' },
  { code: '9991', description: 'Public administration and other government services', gst_rate: 0, category: 'Services - Government' },
  { code: '9992', description: 'Education services', gst_rate: 0, category: 'Services - Education' },
  { code: '9993', description: 'Human health and social care services', gst_rate: 0, category: 'Services - Healthcare' },
  { code: '9994', description: 'Sewage and waste collection, treatment and disposal services', gst_rate: 0, category: 'Services - Utilities' },
  { code: '9995', description: 'Services of membership organisations', gst_rate: 18, category: 'Services - Membership' },
  { code: '9996', description: 'Recreational, cultural and sporting services', gst_rate: 18, category: 'Services - Recreation' },
  { code: '9997', description: 'Other services', gst_rate: 18, category: 'Services - Other' },
  { code: '9998', description: 'Domestic services', gst_rate: 0, category: 'Services - Domestic' }
];

const PINCODE_DATA = [
  // Delhi
  { pincode: '110001', city: 'New Delhi', district: 'New Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110002', city: 'New Delhi', district: 'New Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110003', city: 'New Delhi', district: 'South Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110004', city: 'New Delhi', district: 'New Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110005', city: 'New Delhi', district: 'West Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110006', city: 'New Delhi', district: 'Central Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110007', city: 'New Delhi', district: 'North West Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110008', city: 'New Delhi', district: 'West Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110009', city: 'New Delhi', district: 'North Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110010', city: 'New Delhi', district: 'South West Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110011', city: 'New Delhi', district: 'New Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110012', city: 'New Delhi', district: 'South Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110013', city: 'New Delhi', district: 'South Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110014', city: 'New Delhi', district: 'South Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110015', city: 'New Delhi', district: 'West Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110016', city: 'New Delhi', district: 'South Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110017', city: 'New Delhi', district: 'South West Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110018', city: 'New Delhi', district: 'West Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110019', city: 'New Delhi', district: 'South East Delhi', state: 'Delhi', region: 'North' },
  { pincode: '110020', city: 'New Delhi', district: 'South Delhi', state: 'Delhi', region: 'North' },
  // Mumbai
  { pincode: '400001', city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', region: 'West' },
  { pincode: '400002', city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', region: 'West' },
  { pincode: '400003', city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', region: 'West' },
  { pincode: '400004', city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', region: 'West' },
  { pincode: '400005', city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', region: 'West' },
  { pincode: '400006', city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', region: 'West' },
  { pincode: '400007', city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', region: 'West' },
  { pincode: '400008', city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', region: 'West' },
  { pincode: '400009', city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', region: 'West' },
  { pincode: '400010', city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', region: 'West' },
  { pincode: '400011', city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', region: 'West' },
  { pincode: '400012', city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', region: 'West' },
  { pincode: '400013', city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', region: 'West' },
  { pincode: '400014', city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', region: 'West' },
  { pincode: '400015', city: 'Mumbai', district: 'Mumbai Suburban', state: 'Maharashtra', region: 'West' },
  { pincode: '400016', city: 'Mumbai', district: 'Mumbai Suburban', state: 'Maharashtra', region: 'West' },
  { pincode: '400017', city: 'Mumbai', district: 'Mumbai Suburban', state: 'Maharashtra', region: 'West' },
  { pincode: '400018', city: 'Mumbai', district: 'Mumbai Suburban', state: 'Maharashtra', region: 'West' },
  { pincode: '400019', city: 'Mumbai', district: 'Mumbai Suburban', state: 'Maharashtra', region: 'West' },
  { pincode: '400020', city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', region: 'West' },
  { pincode: '400050', city: 'Bandra', district: 'Mumbai Suburban', state: 'Maharashtra', region: 'West' },
  { pincode: '400051', city: 'Bandra', district: 'Mumbai Suburban', state: 'Maharashtra', region: 'West' },
  { pincode: '400059', city: 'Andheri', district: 'Mumbai Suburban', state: 'Maharashtra', region: 'West' },
  { pincode: '400070', city: 'Kurla', district: 'Mumbai Suburban', state: 'Maharashtra', region: 'West' },
  { pincode: '400093', city: 'Powai', district: 'Mumbai Suburban', state: 'Maharashtra', region: 'West' },
  // Bengaluru
  { pincode: '560001', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560002', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560003', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560004', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560005', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560006', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560007', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560008', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560009', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560010', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560011', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560012', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560013', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560014', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560015', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560016', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560017', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560018', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560019', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560020', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560025', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560029', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560034', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560037', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560038', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560040', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560043', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560045', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560066', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560068', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560076', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560078', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560100', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  { pincode: '560103', city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', region: 'South' },
  // Chennai
  { pincode: '600001', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600002', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600003', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600004', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600005', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600006', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600007', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600008', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600009', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600010', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600011', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600012', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600013', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600014', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600017', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600018', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600020', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600028', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600033', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600035', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600040', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600041', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600042', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600045', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  { pincode: '600050', city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', region: 'South' },
  // Hyderabad
  { pincode: '500001', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500002', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500003', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500004', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500005', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500006', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500007', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500008', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500009', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500010', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500018', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500032', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500034', city: 'Hyderabad', district: 'Rangareddi', state: 'Telangana', region: 'South' },
  { pincode: '500049', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500050', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500060', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500081', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500082', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  { pincode: '500084', city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', region: 'South' },
  // Kolkata
  { pincode: '700001', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700002', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700003', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700004', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700005', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700006', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700007', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700008', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700009', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700010', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700011', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700012', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700013', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700014', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700015', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700017', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700019', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700020', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700026', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  { pincode: '700027', city: 'Kolkata', district: 'Kolkata', state: 'West Bengal', region: 'East' },
  // Pune
  { pincode: '411001', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411002', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411003', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411004', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411005', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411006', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411007', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411008', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411009', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411010', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411011', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411012', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411013', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411014', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411015', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411016', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411017', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411018', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411019', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411020', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411021', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411027', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411028', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411030', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411033', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411036', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411040', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411041', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411045', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  { pincode: '411046', city: 'Pune', district: 'Pune', state: 'Maharashtra', region: 'West' },
  // Ahmedabad
  { pincode: '380001', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380002', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380003', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380004', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380005', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380006', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380007', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380008', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380009', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380013', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380015', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380016', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380019', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380021', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380022', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380023', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380024', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380025', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380026', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  { pincode: '380027', city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat', region: 'West' },
  // Jaipur
  { pincode: '302001', city: 'Jaipur', district: 'Jaipur', state: 'Rajasthan', region: 'North' },
  { pincode: '302002', city: 'Jaipur', district: 'Jaipur', state: 'Rajasthan', region: 'North' },
  { pincode: '302003', city: 'Jaipur', district: 'Jaipur', state: 'Rajasthan', region: 'North' },
  { pincode: '302004', city: 'Jaipur', district: 'Jaipur', state: 'Rajasthan', region: 'North' },
  { pincode: '302005', city: 'Jaipur', district: 'Jaipur', state: 'Rajasthan', region: 'North' },
  { pincode: '302006', city: 'Jaipur', district: 'Jaipur', state: 'Rajasthan', region: 'North' },
  { pincode: '302007', city: 'Jaipur', district: 'Jaipur', state: 'Rajasthan', region: 'North' },
  { pincode: '302010', city: 'Jaipur', district: 'Jaipur', state: 'Rajasthan', region: 'North' },
  { pincode: '302011', city: 'Jaipur', district: 'Jaipur', state: 'Rajasthan', region: 'North' },
  { pincode: '302012', city: 'Jaipur', district: 'Jaipur', state: 'Rajasthan', region: 'North' },
  { pincode: '302016', city: 'Jaipur', district: 'Jaipur', state: 'Rajasthan', region: 'North' },
  { pincode: '302017', city: 'Jaipur', district: 'Jaipur', state: 'Rajasthan', region: 'North' },
  { pincode: '302019', city: 'Jaipur', district: 'Jaipur', state: 'Rajasthan', region: 'North' },
  { pincode: '302020', city: 'Jaipur', district: 'Jaipur', state: 'Rajasthan', region: 'North' },
  { pincode: '302021', city: 'Jaipur', district: 'Jaipur', state: 'Rajasthan', region: 'North' },
  // Lucknow
  { pincode: '226001', city: 'Lucknow', district: 'Lucknow', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '226002', city: 'Lucknow', district: 'Lucknow', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '226003', city: 'Lucknow', district: 'Lucknow', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '226004', city: 'Lucknow', district: 'Lucknow', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '226005', city: 'Lucknow', district: 'Lucknow', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '226006', city: 'Lucknow', district: 'Lucknow', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '226007', city: 'Lucknow', district: 'Lucknow', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '226008', city: 'Lucknow', district: 'Lucknow', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '226009', city: 'Lucknow', district: 'Lucknow', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '226010', city: 'Lucknow', district: 'Lucknow', state: 'Uttar Pradesh', region: 'North' },
  // Chandigarh
  { pincode: '160001', city: 'Chandigarh', district: 'Chandigarh', state: 'Chandigarh', region: 'North' },
  { pincode: '160002', city: 'Chandigarh', district: 'Chandigarh', state: 'Chandigarh', region: 'North' },
  { pincode: '160003', city: 'Chandigarh', district: 'Chandigarh', state: 'Chandigarh', region: 'North' },
  { pincode: '160011', city: 'Chandigarh', district: 'Chandigarh', state: 'Chandigarh', region: 'North' },
  { pincode: '160014', city: 'Chandigarh', district: 'Chandigarh', state: 'Chandigarh', region: 'North' },
  { pincode: '160015', city: 'Chandigarh', district: 'Chandigarh', state: 'Chandigarh', region: 'North' },
  { pincode: '160017', city: 'Chandigarh', district: 'Chandigarh', state: 'Chandigarh', region: 'North' },
  { pincode: '160019', city: 'Chandigarh', district: 'Chandigarh', state: 'Chandigarh', region: 'North' },
  { pincode: '160020', city: 'Chandigarh', district: 'Chandigarh', state: 'Chandigarh', region: 'North' },
  { pincode: '160022', city: 'Chandigarh', district: 'Chandigarh', state: 'Chandigarh', region: 'North' },
  // Surat
  { pincode: '395001', city: 'Surat', district: 'Surat', state: 'Gujarat', region: 'West' },
  { pincode: '395002', city: 'Surat', district: 'Surat', state: 'Gujarat', region: 'West' },
  { pincode: '395003', city: 'Surat', district: 'Surat', state: 'Gujarat', region: 'West' },
  { pincode: '395004', city: 'Surat', district: 'Surat', state: 'Gujarat', region: 'West' },
  { pincode: '395005', city: 'Surat', district: 'Surat', state: 'Gujarat', region: 'West' },
  { pincode: '395006', city: 'Surat', district: 'Surat', state: 'Gujarat', region: 'West' },
  { pincode: '395007', city: 'Surat', district: 'Surat', state: 'Gujarat', region: 'West' },
  { pincode: '395008', city: 'Surat', district: 'Surat', state: 'Gujarat', region: 'West' },
  { pincode: '395009', city: 'Surat', district: 'Surat', state: 'Gujarat', region: 'West' },
  { pincode: '395010', city: 'Surat', district: 'Surat', state: 'Gujarat', region: 'West' },
  // Nagpur
  { pincode: '440001', city: 'Nagpur', district: 'Nagpur', state: 'Maharashtra', region: 'West' },
  { pincode: '440002', city: 'Nagpur', district: 'Nagpur', state: 'Maharashtra', region: 'West' },
  { pincode: '440003', city: 'Nagpur', district: 'Nagpur', state: 'Maharashtra', region: 'West' },
  { pincode: '440004', city: 'Nagpur', district: 'Nagpur', state: 'Maharashtra', region: 'West' },
  { pincode: '440005', city: 'Nagpur', district: 'Nagpur', state: 'Maharashtra', region: 'West' },
  { pincode: '440006', city: 'Nagpur', district: 'Nagpur', state: 'Maharashtra', region: 'West' },
  { pincode: '440007', city: 'Nagpur', district: 'Nagpur', state: 'Maharashtra', region: 'West' },
  { pincode: '440008', city: 'Nagpur', district: 'Nagpur', state: 'Maharashtra', region: 'West' },
  { pincode: '440009', city: 'Nagpur', district: 'Nagpur', state: 'Maharashtra', region: 'West' },
  { pincode: '440010', city: 'Nagpur', district: 'Nagpur', state: 'Maharashtra', region: 'West' },
  // Patna
  { pincode: '800001', city: 'Patna', district: 'Patna', state: 'Bihar', region: 'East' },
  { pincode: '800002', city: 'Patna', district: 'Patna', state: 'Bihar', region: 'East' },
  { pincode: '800003', city: 'Patna', district: 'Patna', state: 'Bihar', region: 'East' },
  { pincode: '800004', city: 'Patna', district: 'Patna', state: 'Bihar', region: 'East' },
  { pincode: '800005', city: 'Patna', district: 'Patna', state: 'Bihar', region: 'East' },
  { pincode: '800006', city: 'Patna', district: 'Patna', state: 'Bihar', region: 'East' },
  { pincode: '800007', city: 'Patna', district: 'Patna', state: 'Bihar', region: 'East' },
  { pincode: '800008', city: 'Patna', district: 'Patna', state: 'Bihar', region: 'East' },
  { pincode: '800009', city: 'Patna', district: 'Patna', state: 'Bihar', region: 'East' },
  { pincode: '800010', city: 'Patna', district: 'Patna', state: 'Bihar', region: 'East' },
  // Bhopal
  { pincode: '462001', city: 'Bhopal', district: 'Bhopal', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '462002', city: 'Bhopal', district: 'Bhopal', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '462003', city: 'Bhopal', district: 'Bhopal', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '462004', city: 'Bhopal', district: 'Bhopal', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '462010', city: 'Bhopal', district: 'Bhopal', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '462011', city: 'Bhopal', district: 'Bhopal', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '462016', city: 'Bhopal', district: 'Bhopal', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '462021', city: 'Bhopal', district: 'Bhopal', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '462022', city: 'Bhopal', district: 'Bhopal', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '462023', city: 'Bhopal', district: 'Bhopal', state: 'Madhya Pradesh', region: 'Central' },
  // Indore
  { pincode: '452001', city: 'Indore', district: 'Indore', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '452002', city: 'Indore', district: 'Indore', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '452003', city: 'Indore', district: 'Indore', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '452004', city: 'Indore', district: 'Indore', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '452005', city: 'Indore', district: 'Indore', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '452006', city: 'Indore', district: 'Indore', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '452007', city: 'Indore', district: 'Indore', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '452008', city: 'Indore', district: 'Indore', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '452009', city: 'Indore', district: 'Indore', state: 'Madhya Pradesh', region: 'Central' },
  { pincode: '452010', city: 'Indore', district: 'Indore', state: 'Madhya Pradesh', region: 'Central' },
  // Noida
  { pincode: '201301', city: 'Noida', district: 'Gautam Buddha Nagar', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '201302', city: 'Noida', district: 'Gautam Buddha Nagar', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '201303', city: 'Noida', district: 'Gautam Buddha Nagar', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '201304', city: 'Noida', district: 'Gautam Buddha Nagar', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '201305', city: 'Noida', district: 'Gautam Buddha Nagar', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '201306', city: 'Noida', district: 'Gautam Buddha Nagar', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '201307', city: 'Noida', district: 'Gautam Buddha Nagar', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '201308', city: 'Noida', district: 'Gautam Buddha Nagar', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '201309', city: 'Noida', district: 'Gautam Buddha Nagar', state: 'Uttar Pradesh', region: 'North' },
  { pincode: '201310', city: 'Noida', district: 'Gautam Buddha Nagar', state: 'Uttar Pradesh', region: 'North' },
  // Gurugram
  { pincode: '122001', city: 'Gurugram', district: 'Gurugram', state: 'Haryana', region: 'North' },
  { pincode: '122002', city: 'Gurugram', district: 'Gurugram', state: 'Haryana', region: 'North' },
  { pincode: '122003', city: 'Gurugram', district: 'Gurugram', state: 'Haryana', region: 'North' },
  { pincode: '122004', city: 'Gurugram', district: 'Gurugram', state: 'Haryana', region: 'North' },
  { pincode: '122005', city: 'Gurugram', district: 'Gurugram', state: 'Haryana', region: 'North' },
  { pincode: '122006', city: 'Gurugram', district: 'Gurugram', state: 'Haryana', region: 'North' },
  { pincode: '122007', city: 'Gurugram', district: 'Gurugram', state: 'Haryana', region: 'North' },
  { pincode: '122008', city: 'Gurugram', district: 'Gurugram', state: 'Haryana', region: 'North' },
  { pincode: '122009', city: 'Gurugram', district: 'Gurugram', state: 'Haryana', region: 'North' },
  { pincode: '122010', city: 'Gurugram', district: 'Gurugram', state: 'Haryana', region: 'North' },
  { pincode: '122015', city: 'Gurugram', district: 'Gurugram', state: 'Haryana', region: 'North' },
  { pincode: '122016', city: 'Gurugram', district: 'Gurugram', state: 'Haryana', region: 'North' },
  { pincode: '122018', city: 'Gurugram', district: 'Gurugram', state: 'Haryana', region: 'North' },
  { pincode: '122022', city: 'Gurugram', district: 'Gurugram', state: 'Haryana', region: 'North' },
  // Coimbatore
  { pincode: '641001', city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu', region: 'South' },
  { pincode: '641002', city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu', region: 'South' },
  { pincode: '641003', city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu', region: 'South' },
  { pincode: '641004', city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu', region: 'South' },
  { pincode: '641005', city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu', region: 'South' },
  { pincode: '641006', city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu', region: 'South' },
  { pincode: '641007', city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu', region: 'South' },
  { pincode: '641008', city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu', region: 'South' },
  { pincode: '641009', city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu', region: 'South' },
  { pincode: '641010', city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu', region: 'South' },
  // Kochi
  { pincode: '682001', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682002', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682003', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682004', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682005', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682006', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682007', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682008', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682009', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682010', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682011', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682012', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682013', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682014', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682015', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682016', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682017', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682018', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682019', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' },
  { pincode: '682020', city: 'Kochi', district: 'Ernakulam', state: 'Kerala', region: 'South' }
];

export async function seed() {
  console.log('Seeding HSN codes...');
  let hsnCount = 0;
  for (const h of HSN_CODES) {
    try {
      insertHsn(h.code, h.description, h.gst_rate, h.category);
      hsnCount++;
    } catch {
      // Skip duplicates
    }
  }
  console.log(`Seeded ${hsnCount} HSN/SAC codes.`);

  console.log('Seeding PIN codes...');
  let pinCount = 0;
  for (const p of PINCODE_DATA) {
    try {
      insertPincode(p.pincode, p.city, p.district, p.state, p.region);
      pinCount++;
    } catch {
      // Skip duplicates
    }
  }
  console.log(`Seeded ${pinCount} PIN codes.`);
}

// Run if executed directly
seed().then(() => {
  console.log('Seed complete.');
  process.exit(0);
}).catch(err => {
  console.error('Seed failed:', err);
  process.exit(1);
});
